name: zero
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.5
  fluttertoast: ^8.2.12
  pinput: ^5.0.1
  intl: ^0.20.2
  animated_notch_bottom_bar: ^1.0.3
  shared_preferences: ^2.5.2
  timeago: ^3.2.2
  animated_splash_screen: ^1.3.0
  expandable: ^5.0.1
  fl_chart: ^0.70.2
  get: ^4.7.2
  image_picker: ^1.2.0
  hive_flutter: ^1.1.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  flutter_upi_india: ^1.0.1
  # razorpay_flutter: ^1.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_foreground: "assets/icons/app_logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/
